name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Read Firefly version - major
        uses: bfren/read-file@v1
        with:
          file: ./FIREFLY_MAJOR
        id: firefly_major
      -
        name: Read Firefly version - minor
        uses: bfren/read-file@v1
        with:
          file: ./FIREFLY_MINOR
        id: firefly_minor
      -
        name: Read Firefly version - version
        uses: bfren/read-file@v1
        with:
          file: ./FIREFLY_VERSION
        id: firefly_version
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            bfren/firefly:latest
            bfren/firefly:${{ steps.version.outputs.contents }}
            bfren/firefly:firefly${{ steps.firefly_major.outputs.contents }}
            bfren/firefly:firefly${{ steps.firefly_major.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/firefly:firefly${{ steps.firefly_minor.outputs.contents }}
            bfren/firefly:firefly${{ steps.firefly_minor.outputs.contents }}-${{ steps.version.outputs.contents }}
            bfren/firefly:firefly${{ steps.firefly_version.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
